import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

// DSA Easy Curated topics
const NEETCODE_ALL_TOPICS = [
  "Arrays & Hashing",
  "Two Pointers",
  "Sliding Window",
  "Stack",
  "Binary Search",
  "Linked List",
  "Trees",
  "Tries",
  "Heap / Priority Queue",
  "Backtracking",
  "Graphs",
  "1-D DP",
  "Intervals",
  "Greedy",
  "Advanced Graphs",
  "Math & Geometry",
  "2-D DP",
  "Bit Manipulation",
];

// Complete DSA Easy Curated problem list - all 954 problems
// Format: [title, difficulty, topic, leetcodeNumber, acceptanceRate]
const ALL_PROBLEMS: [string, string, string, number, number][] = [
  // ===== Arrays & Hashing (beyond 150) =====
  ["Contains Duplicate", "Easy", "Arrays & Hashing", 217, 61.2],
  ["Valid Anagram", "Easy", "Arrays & Hashing", 242, 63.5],
  ["Two Sum", "Easy", "Arrays & Hashing", 1, 52.5],
  ["Group Anagrams", "Medium", "Arrays & Hashing", 49, 67.4],
  ["Top K Frequent Elements", "Medium", "Arrays & Hashing", 347, 64.2],
  ["Encode and Decode Strings", "Medium", "Arrays & Hashing", 271, 45.0],
  ["Product of Array Except Self", "Medium", "Arrays & Hashing", 238, 65.5],
  ["Valid Sudoku", "Medium", "Arrays & Hashing", 36, 58.4],
  ["Longest Consecutive Sequence", "Medium", "Arrays & Hashing", 128, 47.5],
  ["Sort Colors", "Medium", "Arrays & Hashing", 75, 61.4],
  ["Next Permutation", "Medium", "Arrays & Hashing", 31, 39.0],
  ["Find the Duplicate Number", "Medium", "Arrays & Hashing", 287, 59.5],
  ["First Missing Positive", "Hard", "Arrays & Hashing", 41, 37.2],
  ["Largest Rectangle in Histogram", "Hard", "Arrays & Hashing", 84, 43.5],
  ["Subarray Sum Equals K", "Medium", "Arrays & Hashing", 560, 44.2],
  ["Range Sum Query - Immutable", "Easy", "Arrays & Hashing", 303, 59.8],
  ["Range Sum Query 2D - Immutable", "Medium", "Arrays & Hashing", 304, 52.3],
  ["Find All Numbers Disappeared in an Array", "Easy", "Arrays & Hashing", 448, 60.5],
  ["Maximum Product Subarray", "Medium", "Arrays & Hashing", 152, 34.8],
  ["Pascal's Triangle", "Easy", "Arrays & Hashing", 118, 73.2],
  ["Pascal's Triangle II", "Easy", "Arrays & Hashing", 119, 63.0],
  ["Remove Duplicates from Sorted Array", "Easy", "Arrays & Hashing", 26, 53.8],
  ["Remove Element", "Easy", "Arrays & Hashing", 27, 55.2],
  ["Find First and Last Position of Element in Sorted Array", "Medium", "Arrays & Hashing", 34, 42.8],
  ["Insert Delete GetRandom O(1)", "Medium", "Arrays & Hashing", 380, 53.8],
  ["Brick Wall", "Medium", "Arrays & Hashing", 554, 54.5],
  ["Best Time to Buy and Sell Stock II", "Medium", "Arrays & Hashing", 122, 65.4],
  ["Majority Element", "Easy", "Arrays & Hashing", 169, 64.8],
  ["Majority Element II", "Medium", "Arrays & Hashing", 229, 48.2],
  ["Push Dominoes", "Medium", "Arrays & Hashing", 838, 57.5],
  ["Design HashSet", "Easy", "Arrays & Hashing", 705, 66.0],
  ["Design HashMap", "Easy", "Arrays & Hashing", 706, 64.7],
  ["Continuous Subarray Sum", "Medium", "Arrays & Hashing", 523, 28.7],
  ["Grid Game", "Medium", "Arrays & Hashing", 2017, 43.8],
  ["Num Array", "Easy", "Arrays & Hashing", 303, 59.8],
  ["Maximum Number of Balloons", "Easy", "Arrays & Hashing", 1189, 62.3],
  ["Word Pattern", "Easy", "Arrays & Hashing", 290, 42.0],
  ["Design Twitter", "Medium", "Arrays & Hashing", 355, 37.2],
  ["Number of Zero-Filled Subarrays", "Medium", "Arrays & Hashing", 2348, 58.7],
  ["Custom Sort String", "Medium", "Arrays & Hashing", 791, 70.3],
  ["Sort an Array", "Medium", "Arrays & Hashing", 912, 55.2],
  ["Non-decreasing Subsequences", "Medium", "Arrays & Hashing", 491, 58.0],
  ["Wiggle Sort", "Medium", "Arrays & Hashing", 280, 68.0],
  ["Longest Common Prefix", "Easy", "Arrays & Hashing", 14, 42.5],

  // ===== Two Pointers =====
  ["Valid Palindrome", "Easy", "Two Pointers", 125, 46.2],
  ["Two Sum II - Input Array Is Sorted", "Medium", "Two Pointers", 167, 61.5],
  ["3Sum", "Medium", "Two Pointers", 15, 33.5],
  ["Container With Most Water", "Medium", "Two Pointers", 11, 55.5],
  ["Trapping Rain Water", "Hard", "Two Pointers", 42, 60.5],
  ["4Sum", "Medium", "Two Pointers", 18, 37.2],
  ["Remove Duplicates from Sorted Array II", "Medium", "Two Pointers", 80, 57.5],
  ["Rotate Array", "Medium", "Two Pointers", 189, 39.8],
  ["Boats to Save People", "Medium", "Two Pointers", 881, 54.8],
  ["Merge Sorted Array", "Easy", "Two Pointers", 88, 48.5],
  ["Move Zeroes", "Easy", "Two Pointers", 283, 61.8],
  ["Squares of a Sorted Array", "Easy", "Two Pointers", 977, 72.5],
  ["Assign Cookies", "Easy", "Two Pointers", 455, 50.8],
  ["Number of Subsequences That Satisfy the Given Sum Condition", "Medium", "Two Pointers", 1498, 39.8],
  ["Rearrange Array Elements by Sign", "Medium", "Two Pointers", 2149, 81.2],

  // ===== Sliding Window =====
  ["Best Time to Buy and Sell Stock", "Easy", "Sliding Window", 121, 54.2],
  ["Longest Substring Without Repeating Characters", "Medium", "Sliding Window", 3, 34.5],
  ["Longest Repeating Character Replacement", "Medium", "Sliding Window", 424, 53.5],
  ["Permutation in String", "Medium", "Sliding Window", 567, 44.5],
  ["Minimum Window Substring", "Hard", "Sliding Window", 76, 41.0],
  ["Sliding Window Maximum", "Hard", "Sliding Window", 239, 46.5],
  ["Minimum Size Subarray Sum", "Medium", "Sliding Window", 209, 46.5],
  ["Frequency of the Most Frequent Element", "Medium", "Sliding Window", 1838, 38.2],
  ["Fruits Into Baskets", "Medium", "Sliding Window", 904, 45.5],
  ["Maximum Number of Vowels in a Substring of Given Length", "Medium", "Sliding Window", 1456, 58.5],
  ["Minimum Number of Flips to Make the Binary String Alternating", "Medium", "Sliding Window", 1888, 40.2],
  ["Count Number of Nice Subarrays", "Medium", "Sliding Window", 1248, 61.5],
  ["Longest Subarray of 1's After Deleting One Element", "Medium", "Sliding Window", 1493, 63.2],
  ["Substring With Concatenation of All Words", "Hard", "Sliding Window", 30, 31.5],
  ["Minimum Window Subsequence", "Hard", "Sliding Window", 727, 46.0],

  // ===== Stack =====
  ["Valid Parentheses", "Easy", "Stack", 20, 40.2],
  ["Min Stack", "Medium", "Stack", 155, 53.5],
  ["Evaluate Reverse Polish Notation", "Medium", "Stack", 150, 47.5],
  ["Generate Parentheses", "Medium", "Stack", 22, 74.2],
  ["Daily Temperatures", "Medium", "Stack", 739, 66.5],
  ["Car Fleet", "Medium", "Stack", 853, 49.5],
  ["Largest Rectangle in Histogram", "Hard", "Stack", 84, 43.5],
  ["Simplify Path", "Medium", "Stack", 71, 42.8],
  ["Removing Stars From a String", "Medium", "Stack", 2390, 72.5],
  ["Asteroid Collision", "Medium", "Stack", 735, 44.5],
  ["Online Stock Span", "Medium", "Stack", 901, 65.2],
  ["Validate Stack Sequences", "Medium", "Stack", 946, 68.5],
  ["Decode String", "Medium", "Stack", 394, 58.5],
  ["Remove All Adjacent Duplicates in String II", "Medium", "Stack", 1209, 58.2],
  ["132 Pattern", "Medium", "Stack", 456, 33.8],
  ["Maximum Frequency Stack", "Hard", "Stack", 895, 66.2],
  ["Implement Stack using Queues", "Easy", "Stack", 225, 60.2],
  ["Implement Queue using Stacks", "Easy", "Stack", 232, 64.5],
  ["Baseball Game", "Easy", "Stack", 682, 74.2],

  // ===== Binary Search =====
  ["Binary Search", "Easy", "Binary Search", 704, 56.2],
  ["Search a 2D Matrix", "Medium", "Binary Search", 74, 49.5],
  ["Koko Eating Bananas", "Medium", "Binary Search", 875, 49.0],
  ["Find Minimum in Rotated Sorted Array", "Medium", "Binary Search", 153, 50.5],
  ["Search in Rotated Sorted Array", "Medium", "Binary Search", 33, 40.5],
  ["Time Based Key-Value Store", "Medium", "Binary Search", 981, 49.0],
  ["Median of Two Sorted Arrays", "Hard", "Binary Search", 4, 39.5],
  ["Guess Number Higher or Lower", "Easy", "Binary Search", 374, 52.8],
  ["Successful Pairs of Spells and Potions", "Medium", "Binary Search", 2300, 42.5],
  ["Find Peak Element", "Medium", "Binary Search", 162, 46.2],
  ["Search in Rotated Sorted Array II", "Medium", "Binary Search", 81, 36.8],
  ["Find First and Last Position of Element in Sorted Array", "Medium", "Binary Search", 34, 42.8],
  ["Single Element in a Sorted Array", "Medium", "Binary Search", 540, 58.8],
  ["Capacity To Ship Packages Within D Days", "Medium", "Binary Search", 1011, 67.5],
  ["Split Array Largest Sum", "Hard", "Binary Search", 410, 54.5],

  // ===== Linked List =====
  ["Reverse Linked List", "Easy", "Linked List", 206, 75.5],
  ["Merge Two Sorted Lists", "Easy", "Linked List", 21, 63.5],
  ["Reorder List", "Medium", "Linked List", 143, 54.5],
  ["Remove Nth Node From End of List", "Medium", "Linked List", 19, 43.5],
  ["Copy List with Random Pointer", "Medium", "Linked List", 138, 53.5],
  ["Add Two Numbers", "Medium", "Linked List", 2, 42.5],
  ["Linked List Cycle", "Easy", "Linked List", 141, 47.5],
  ["Find the Duplicate Number", "Medium", "Linked List", 287, 59.5],
  ["LRU Cache", "Medium", "Linked List", 146, 41.5],
  ["Merge k Sorted Lists", "Hard", "Linked List", 23, 52.5],
  ["Reverse Linked List II", "Medium", "Linked List", 92, 47.2],
  ["Rotate List", "Medium", "Linked List", 61, 37.8],
  ["Swap Nodes in Pairs", "Medium", "Linked List", 24, 63.2],
  ["Sort List", "Medium", "Linked List", 148, 56.2],
  ["Partition List", "Medium", "Linked List", 86, 54.8],
  ["Remove Duplicates from Sorted List", "Easy", "Linked List", 83, 52.5],
  ["Remove Duplicates from Sorted List II", "Medium", "Linked List", 82, 47.2],
  ["Palindrome Linked List", "Easy", "Linked List", 234, 52.5],
  ["Design Browser History", "Medium", "Linked List", 1472, 77.8],
  ["Middle of the Linked List", "Easy", "Linked List", 876, 76.2],
  ["Maximum Twin Sum of a Linked List", "Medium", "Linked List", 2130, 82.5],
  ["Odd Even Linked List", "Medium", "Linked List", 328, 62.8],
  ["Design Linked List", "Medium", "Linked List", 707, 28.5],
  ["Intersection of Two Linked Lists", "Easy", "Linked List", 160, 57.2],
  ["Flatten a Multilevel Doubly Linked List", "Medium", "Linked List", 430, 60.5],
  ["Reverse Nodes in k-Group", "Hard", "Linked List", 25, 56.8],

  // ===== Trees =====
  ["Invert Binary Tree", "Easy", "Trees", 226, 76.2],
  ["Maximum Depth of Binary Tree", "Easy", "Trees", 104, 74.5],
  ["Diameter of Binary Tree", "Easy", "Trees", 543, 58.2],
  ["Balanced Binary Tree", "Easy", "Trees", 110, 50.5],
  ["Same Tree", "Easy", "Trees", 100, 58.5],
  ["Subtree of Another Tree", "Easy", "Trees", 572, 46.5],
  ["Lowest Common Ancestor of a Binary Search Tree", "Medium", "Trees", 235, 62.5],
  ["Binary Tree Level Order Traversal", "Medium", "Trees", 102, 66.5],
  ["Binary Tree Right Side View", "Medium", "Trees", 199, 62.5],
  ["Count Good Nodes in Binary Tree", "Medium", "Trees", 1448, 64.5],
  ["Validate Binary Search Tree", "Medium", "Trees", 98, 32.5],
  ["Kth Smallest Element in a BST", "Medium", "Trees", 230, 71.5],
  ["Construct Binary Tree from Preorder and Inorder Traversal", "Medium", "Trees", 105, 63.5],
  ["Binary Tree Maximum Path Sum", "Hard", "Trees", 124, 39.5],
  ["Serialize and Deserialize Binary Tree", "Hard", "Trees", 297, 55.5],
  ["Binary Tree Zigzag Level Order Traversal", "Medium", "Trees", 103, 56.8],
  ["Path Sum", "Easy", "Trees", 112, 49.5],
  ["Path Sum II", "Medium", "Trees", 113, 57.8],
  ["Path Sum III", "Medium", "Trees", 437, 49.2],
  ["Sum Root to Leaf Numbers", "Medium", "Trees", 129, 63.8],
  ["Binary Search Tree Iterator", "Medium", "Trees", 173, 72.5],
  ["Populating Next Right Pointers in Each Node", "Medium", "Trees", 116, 62.5],
  ["Flatten Binary Tree to Linked List", "Medium", "Trees", 114, 63.2],
  ["Convert Sorted Array to Binary Search Tree", "Easy", "Trees", 108, 70.5],
  ["Symmetric Tree", "Easy", "Trees", 101, 54.8],
  ["Minimum Depth of Binary Tree", "Easy", "Trees", 111, 45.2],
  ["House Robber III", "Medium", "Trees", 337, 53.8],
  ["Binary Tree Preorder Traversal", "Easy", "Trees", 144, 66.5],
  ["Binary Tree Inorder Traversal", "Easy", "Trees", 94, 75.8],
  ["Binary Tree Postorder Traversal", "Easy", "Trees", 145, 68.2],
  ["Unique Binary Search Trees", "Medium", "Trees", 96, 60.5],
  ["Unique Binary Search Trees II", "Medium", "Trees", 95, 55.2],
  ["Delete Node in a BST", "Medium", "Trees", 450, 50.2],
  ["Trim a Binary Search Tree", "Medium", "Trees", 669, 66.8],
  ["Construct Binary Tree from Inorder and Postorder Traversal", "Medium", "Trees", 106, 60.5],
  ["Maximum Width of Binary Tree", "Medium", "Trees", 662, 42.8],
  ["Binary Tree Cameras", "Hard", "Trees", 968, 46.2],
  ["Recover Binary Search Tree", "Medium", "Trees", 99, 50.8],
  ["All Nodes Distance K in Binary Tree", "Medium", "Trees", 863, 63.2],
  ["Vertical Order Traversal of a Binary Tree", "Hard", "Trees", 987, 45.5],
  ["Leaf-Similar Trees", "Easy", "Trees", 872, 65.8],
  ["Count Complete Tree Nodes", "Medium", "Trees", 222, 62.5],
  ["Lowest Common Ancestor of a Binary Tree", "Medium", "Trees", 236, 61.2],
  ["Check Completeness of a Binary Tree", "Medium", "Trees", 958, 55.8],
  ["Average of Levels in Binary Tree", "Easy", "Trees", 637, 72.5],
  ["N-ary Tree Level Order Traversal", "Medium", "Trees", 429, 71.5],
  ["Cousins in Binary Tree", "Easy", "Trees", 993, 54.8],
  ["Sum of Left Leaves", "Easy", "Trees", 404, 57.2],
  ["Univalued Binary Tree", "Easy", "Trees", 965, 70.2],
  ["Find Bottom Left Tree Value", "Medium", "Trees", 513, 67.5],
  ["Even Odd Tree", "Medium", "Trees", 1609, 54.2],
  ["Amount of Time for Binary Tree to Be Infected", "Medium", "Trees", 2385, 58.5],
  ["Operations on Tree", "Medium", "Trees", 1993, 46.2],
  ["Maximum Level Sum of a Binary Tree", "Medium", "Trees", 1161, 68.5],
  ["Minimum Distance Between BST Nodes", "Easy", "Trees", 783, 58.2],

  // ===== Tries =====
  ["Implement Trie (Prefix Tree)", "Medium", "Tries", 208, 63.5],
  ["Design Add and Search Words Data Structure", "Medium", "Tries", 211, 44.5],
  ["Word Search II", "Hard", "Tries", 212, 36.5],
  ["Replace Words", "Medium", "Tries", 648, 64.5],
  ["Extra Characters in a String", "Medium", "Tries", 2707, 52.2],
  ["Search Suggestions System", "Medium", "Tries", 1268, 67.5],
  ["Implement Magic Dictionary", "Medium", "Tries", 676, 57.8],
  ["Map Sum Pairs", "Medium", "Tries", 677, 55.2],

  // ===== Heap / Priority Queue =====
  ["Kth Largest Element in a Stream", "Easy", "Heap / Priority Queue", 703, 56.5],
  ["Last Stone Weight", "Easy", "Heap / Priority Queue", 1046, 65.5],
  ["K Closest Points to Origin", "Medium", "Heap / Priority Queue", 973, 66.5],
  ["Kth Largest Element in an Array", "Medium", "Heap / Priority Queue", 215, 66.5],
  ["Task Scheduler", "Medium", "Heap / Priority Queue", 621, 58.5],
  ["Design Twitter", "Medium", "Heap / Priority Queue", 355, 37.2],
  ["Find Median from Data Stream", "Hard", "Heap / Priority Queue", 295, 51.5],
  ["IPO", "Hard", "Heap / Priority Queue", 502, 50.2],
  ["Find K Pairs with Smallest Sums", "Medium", "Heap / Priority Queue", 373, 39.8],
  ["Seat Reservation Manager", "Medium", "Heap / Priority Queue", 1845, 65.8],
  ["Process Tasks Using Servers", "Medium", "Heap / Priority Queue", 1882, 39.2],
  ["Reorganize String", "Medium", "Heap / Priority Queue", 767, 54.5],
  ["Longest Happy String", "Medium", "Heap / Priority Queue", 1405, 58.2],
  ["Car Pooling", "Medium", "Heap / Priority Queue", 1094, 58.8],
  ["Top K Frequent Words", "Medium", "Heap / Priority Queue", 692, 57.8],
  ["Ugly Number II", "Medium", "Heap / Priority Queue", 264, 47.5],
  ["Single-Threaded CPU", "Medium", "Heap / Priority Queue", 1834, 44.5],
  ["K-th Smallest Prime Fraction", "Medium", "Heap / Priority Queue", 786, 55.5],
  ["Smallest Number in Infinite Set", "Medium", "Heap / Priority Queue", 2336, 73.5],
  ["Maximum Subsequence Score", "Medium", "Heap / Priority Queue", 2542, 54.2],
  ["Total Cost to Hire K Workers", "Medium", "Heap / Priority Queue", 2462, 41.2],

  // ===== Backtracking =====
  ["Subsets", "Medium", "Backtracking", 78, 76.5],
  ["Combination Sum", "Medium", "Backtracking", 39, 70.5],
  ["Permutations", "Medium", "Backtracking", 46, 77.5],
  ["Subsets II", "Medium", "Backtracking", 90, 56.5],
  ["Combination Sum II", "Medium", "Backtracking", 40, 54.5],
  ["Word Search", "Medium", "Backtracking", 79, 42.5],
  ["Palindrome Partitioning", "Medium", "Backtracking", 131, 65.5],
  ["Letter Combinations of a Phone Number", "Medium", "Backtracking", 17, 60.5],
  ["N-Queens", "Hard", "Backtracking", 51, 65.5],
  ["Combinations", "Medium", "Backtracking", 77, 69.8],
  ["Permutations II", "Medium", "Backtracking", 47, 58.2],
  ["N-Queens II", "Hard", "Backtracking", 52, 75.5],
  ["Sudoku Solver", "Hard", "Backtracking", 37, 58.2],
  ["Restore IP Addresses", "Medium", "Backtracking", 93, 47.5],
  ["Matchsticks to Square", "Medium", "Backtracking", 473, 42.8],
  ["Splitting a String Into Descending Consecutive Values", "Medium", "Backtracking", 1849, 34.5],
  ["Find Unique Binary String", "Medium", "Backtracking", 1980, 66.5],
  ["Maximum Length of a Concatenated String with Unique Characters", "Medium", "Backtracking", 1239, 52.5],
  ["Partition to K Equal Sum Subsets", "Medium", "Backtracking", 698, 36.2],

  // ===== Graphs =====
  ["Number of Islands", "Medium", "Graphs", 200, 57.5],
  ["Clone Graph", "Medium", "Graphs", 133, 53.5],
  ["Max Area of Island", "Medium", "Graphs", 695, 72.5],
  ["Pacific Atlantic Water Flow", "Medium", "Graphs", 417, 53.5],
  ["Surrounded Regions", "Medium", "Graphs", 130, 38.5],
  ["Rotting Oranges", "Medium", "Graphs", 994, 53.5],
  ["Walls and Gates", "Medium", "Graphs", 286, 60.5],
  ["Course Schedule", "Medium", "Graphs", 207, 46.5],
  ["Course Schedule II", "Medium", "Graphs", 210, 49.5],
  ["Graph Valid Tree", "Medium", "Graphs", 261, 47.5],
  ["Number of Connected Components in an Undirected Graph", "Medium", "Graphs", 323, 63.5],
  ["Redundant Connection", "Medium", "Graphs", 684, 63.5],
  ["Word Ladder", "Hard", "Graphs", 127, 38.5],
  ["Open the Lock", "Medium", "Graphs", 752, 59.8],
  ["Snakes and Ladders", "Medium", "Graphs", 909, 42.5],
  ["Find Eventual Safe States", "Medium", "Graphs", 802, 57.2],
  ["Shortest Path in Binary Matrix", "Medium", "Graphs", 1091, 46.2],
  ["Evaluate Division", "Medium", "Graphs", 399, 61.5],
  ["Minimum Height Trees", "Medium", "Graphs", 310, 39.5],
  ["Shortest Bridge", "Medium", "Graphs", 934, 55.8],
  ["Accounts Merge", "Medium", "Graphs", 721, 57.2],
  ["Is Graph Bipartite?", "Medium", "Graphs", 785, 53.5],
  ["Detonate the Maximum Bombs", "Medium", "Graphs", 2101, 43.2],
  ["Keys and Rooms", "Medium", "Graphs", 841, 72.5],
  ["Nearest Exit from Entrance in Maze", "Medium", "Graphs", 1926, 45.5],
  ["Number of Provinces", "Medium", "Graphs", 547, 65.2],
  ["Reorder Routes to Make All Paths Lead to the City Zero", "Medium", "Graphs", 1466, 63.8],
  ["01 Matrix", "Medium", "Graphs", 542, 46.5],
  ["As Far from Land as Possible", "Medium", "Graphs", 1162, 50.2],
  ["Count Sub Islands", "Medium", "Graphs", 1905, 68.5],
  ["Making A Large Island", "Hard", "Graphs", 827, 46.2],
  ["Swim in Rising Water", "Hard", "Graphs", 778, 61.5],
  ["All Paths From Source to Target", "Medium", "Graphs", 797, 82.5],
  ["Number of Enclaves", "Medium", "Graphs", 1020, 67.2],
  ["Number of Closed Islands", "Medium", "Graphs", 1254, 65.8],
  ["Minimum Number of Vertices to Reach All Nodes", "Medium", "Graphs", 1557, 80.5],
  ["Loud and Rich", "Medium", "Graphs", 851, 58.8],
  ["Map of Highest Peak", "Medium", "Graphs", 1765, 59.2],

  // ===== 1-D DP =====
  ["Climbing Stairs", "Easy", "1-D DP", 70, 52.5],
  ["Min Cost Climbing Stairs", "Easy", "1-D DP", 746, 64.5],
  ["House Robber", "Medium", "1-D DP", 198, 49.5],
  ["House Robber II", "Medium", "1-D DP", 213, 41.5],
  ["Longest Palindromic Substring", "Medium", "1-D DP", 5, 33.5],
  ["Palindromic Substrings", "Medium", "1-D DP", 647, 67.5],
  ["Decode Ways", "Medium", "1-D DP", 91, 34.5],
  ["Coin Change", "Medium", "1-D DP", 322, 42.5],
  ["Maximum Product Subarray", "Medium", "1-D DP", 152, 34.5],
  ["Word Break", "Medium", "1-D DP", 139, 46.5],
  ["Longest Increasing Subsequence", "Medium", "1-D DP", 300, 53.5],
  ["Partition Equal Subset Sum", "Medium", "1-D DP", 416, 47.5],
  ["Triangle", "Medium", "1-D DP", 120, 55.8],
  ["Delete and Earn", "Medium", "1-D DP", 740, 58.5],
  ["Jump Game", "Medium", "1-D DP", 55, 38.5],
  ["Jump Game II", "Medium", "1-D DP", 45, 40.2],
  ["Maximum Subarray", "Medium", "1-D DP", 53, 50.5],
  ["Combination Sum IV", "Medium", "1-D DP", 377, 52.5],
  ["Perfect Squares", "Medium", "1-D DP", 279, 53.5],
  ["Ugly Number II", "Medium", "1-D DP", 264, 47.5],
  ["Counting Bits", "Easy", "1-D DP", 338, 76.5],
  ["Integer Break", "Medium", "1-D DP", 343, 55.8],
  ["Longest Turbulent Subarray", "Medium", "1-D DP", 978, 47.8],
  ["Minimum Cost for Tickets", "Medium", "1-D DP", 983, 65.8],
  ["Last Stone Weight II", "Medium", "1-D DP", 1049, 54.2],
  ["Number of Longest Increasing Subsequence", "Medium", "1-D DP", 673, 43.5],
  ["Russian Doll Envelopes", "Hard", "1-D DP", 354, 39.8],
  ["Best Time to Buy and Sell Stock with Cooldown", "Medium", "1-D DP", 309, 56.8],
  ["Coin Change II", "Medium", "1-D DP", 518, 63.2],
  ["Target Sum", "Medium", "1-D DP", 494, 45.5],
  ["Interleaving String", "Medium", "1-D DP", 97, 37.5],
  ["Ones and Zeroes", "Medium", "1-D DP", 474, 47.2],
  ["Longest Common Subsequence", "Medium", "1-D DP", 1143, 59.2],
  ["N-th Tribonacci Number", "Easy", "1-D DP", 1137, 63.8],
  ["Domino and Tromino Tiling", "Medium", "1-D DP", 790, 48.5],
  ["Solving Questions With Brainpower", "Medium", "1-D DP", 2140, 48.2],
  ["Arithmetic Slices", "Medium", "1-D DP", 413, 67.5],
  ["Check if There is a Valid Partition For The Array", "Medium", "1-D DP", 2369, 50.2],
  ["Maximum Alternating Subsequence Sum", "Medium", "1-D DP", 1911, 60.5],
  ["Longest Ideal Subsequence", "Medium", "1-D DP", 2370, 49.5],

  // ===== Intervals =====
  ["Insert Interval", "Medium", "Intervals", 57, 39.5],
  ["Merge Intervals", "Medium", "Intervals", 56, 47.5],
  ["Non-overlapping Intervals", "Medium", "Intervals", 435, 51.5],
  ["Meeting Rooms", "Easy", "Intervals", 252, 58.5],
  ["Meeting Rooms II", "Medium", "Intervals", 253, 51.5],
  ["Minimum Interval to Include Each Query", "Hard", "Intervals", 1851, 50.5],
  ["Minimum Number of Arrows to Burst Balloons", "Medium", "Intervals", 452, 55.2],
  ["Remove Covered Intervals", "Medium", "Intervals", 1288, 57.8],
  ["My Calendar I", "Medium", "Intervals", 729, 57.5],
  ["My Calendar II", "Medium", "Intervals", 731, 54.2],
  ["My Calendar III", "Hard", "Intervals", 732, 72.5],

  // ===== Greedy =====
  ["Maximum Subarray", "Medium", "Greedy", 53, 50.5],
  ["Jump Game", "Medium", "Greedy", 55, 38.5],
  ["Jump Game II", "Medium", "Greedy", 45, 40.2],
  ["Gas Station", "Medium", "Greedy", 134, 45.5],
  ["Hand of Straights", "Medium", "Greedy", 846, 56.5],
  ["Merge Triplets to Form Target Triplet", "Medium", "Greedy", 1899, 65.5],
  ["Partition Labels", "Medium", "Greedy", 763, 79.5],
  ["Valid Parenthesis String", "Medium", "Greedy", 678, 34.5],
  ["Candy", "Hard", "Greedy", 135, 42.5],
  ["Minimum Number of Arrows to Burst Balloons", "Medium", "Greedy", 452, 55.2],
  ["Two City Scheduling", "Medium", "Greedy", 1029, 65.8],
  ["Eliminate Maximum Number of Monsters", "Medium", "Greedy", 1921, 47.2],
  ["Dota2 Senate", "Medium", "Greedy", 649, 41.5],
  ["Maximum Number of Events That Can Be Attended", "Medium", "Greedy", 1353, 34.8],
  ["Minimum Deletions to Make Character Frequencies Unique", "Medium", "Greedy", 1647, 59.2],
  ["Optimal Partition of String", "Medium", "Greedy", 2405, 78.5],
  ["Minimum Add to Make Parentheses Valid", "Medium", "Greedy", 921, 76.2],
  ["Minimum Number of Swaps to Make the String Balanced", "Medium", "Greedy", 1963, 70.8],

  // ===== Advanced Graphs =====
  ["Reconstruct Itinerary", "Hard", "Advanced Graphs", 332, 42.5],
  ["Min Cost to Connect All Points", "Medium", "Advanced Graphs", 1584, 65.5],
  ["Network Delay Time", "Medium", "Advanced Graphs", 743, 52.5],
  ["Swim in Rising Water", "Hard", "Advanced Graphs", 778, 61.5],
  ["Alien Dictionary", "Hard", "Advanced Graphs", 269, 35.5],
  ["Cheapest Flights Within K Stops", "Medium", "Advanced Graphs", 787, 40.5],
  ["Path with Maximum Probability", "Medium", "Advanced Graphs", 1514, 48.2],
  ["Path with Minimum Effort", "Medium", "Advanced Graphs", 1631, 55.8],
  ["Design Graph With Shortest Path Calculator", "Hard", "Advanced Graphs", 2642, 68.2],
  ["Find Critical and Pseudo-Critical Edges in MST", "Hard", "Advanced Graphs", 1489, 57.5],

  // ===== Math & Geometry =====
  ["Rotate Image", "Medium", "Math & Geometry", 48, 72.5],
  ["Spiral Matrix", "Medium", "Math & Geometry", 54, 47.5],
  ["Set Matrix Zeroes", "Medium", "Math & Geometry", 73, 53.5],
  ["Happy Number", "Easy", "Math & Geometry", 202, 55.5],
  ["Plus One", "Easy", "Math & Geometry", 66, 43.5],
  ["Pow(x, n)", "Medium", "Math & Geometry", 50, 34.5],
  ["Multiply Strings", "Medium", "Math & Geometry", 43, 39.5],
  ["Detect Squares", "Medium", "Math & Geometry", 2013, 52.5],
  ["Count Primes", "Medium", "Math & Geometry", 204, 33.5],
  ["Factorial Trailing Zeroes", "Medium", "Math & Geometry", 172, 42.5],
  ["Excel Sheet Column Title", "Easy", "Math & Geometry", 168, 36.8],
  ["Excel Sheet Column Number", "Easy", "Math & Geometry", 171, 63.2],
  ["Roman to Integer", "Easy", "Math & Geometry", 13, 58.5],
  ["Integer to Roman", "Medium", "Math & Geometry", 12, 63.5],
  ["Spiral Matrix II", "Medium", "Math & Geometry", 59, 68.5],
  ["Diagonal Traverse", "Medium", "Math & Geometry", 498, 58.2],
  ["Robot Bounded In Circle", "Medium", "Math & Geometry", 1041, 55.8],
  ["Palindrome Number", "Easy", "Math & Geometry", 9, 55.5],
  ["Sqrt(x)", "Easy", "Math & Geometry", 69, 38.5],
  ["Random Pick with Weight", "Medium", "Math & Geometry", 528, 46.5],
  ["Fizz Buzz", "Easy", "Math & Geometry", 412, 70.5],
  ["Minimum Rounds to Complete All Tasks", "Medium", "Math & Geometry", 2244, 60.5],
  ["Determine if Cell Is Reachable at a Given Time", "Medium", "Math & Geometry", 2849, 35.5],
  ["Insert Greatest Common Divisors in Linked List", "Medium", "Math & Geometry", 2807, 88.2],

  // ===== 2-D DP =====
  ["Unique Paths", "Medium", "2-D DP", 62, 63.5],
  ["Longest Common Subsequence", "Medium", "2-D DP", 1143, 59.5],
  ["Best Time to Buy and Sell Stock with Cooldown", "Medium", "2-D DP", 309, 56.5],
  ["Coin Change II", "Medium", "2-D DP", 518, 63.5],
  ["Target Sum", "Medium", "2-D DP", 494, 45.5],
  ["Interleaving String", "Medium", "2-D DP", 97, 37.5],
  ["Longest Increasing Path in a Matrix", "Hard", "2-D DP", 329, 52.5],
  ["Distinct Subsequences", "Hard", "2-D DP", 115, 45.5],
  ["Edit Distance", "Medium", "2-D DP", 72, 54.5],
  ["Burst Balloons", "Hard", "2-D DP", 312, 58.5],
  ["Regular Expression Matching", "Hard", "2-D DP", 10, 28.5],
  ["Ones and Zeroes", "Medium", "2-D DP", 474, 47.5],
  ["Maximal Square", "Medium", "2-D DP", 221, 45.2],
  ["Minimum Path Sum", "Medium", "2-D DP", 64, 63.8],
  ["Unique Paths II", "Medium", "2-D DP", 63, 40.5],
  ["Dungeon Game", "Hard", "2-D DP", 174, 38.5],
  ["Stone Game", "Medium", "2-D DP", 877, 69.5],
  ["Stone Game II", "Medium", "2-D DP", 1140, 64.8],
  ["Stone Game III", "Hard", "2-D DP", 1406, 62.5],
  ["Profitable Schemes", "Hard", "2-D DP", 879, 47.8],
  ["Last Stone Weight II", "Medium", "2-D DP", 1049, 54.2],
  ["Count Vowels Permutation", "Hard", "2-D DP", 1220, 60.5],
  ["Number of Ways to Rearrange Sticks With K Sticks Visible", "Hard", "2-D DP", 1866, 56.2],
  ["Wildcard Matching", "Hard", "2-D DP", 44, 27.5],
  ["Out of Boundary Paths", "Medium", "2-D DP", 576, 45.5],
  ["Number of Dice Rolls With Target Sum", "Medium", "2-D DP", 1155, 55.2],
  ["Knight Probability in Chessboard", "Medium", "2-D DP", 688, 52.8],
  ["Cherry Pickup", "Hard", "2-D DP", 741, 36.5],
  ["Cherry Pickup II", "Hard", "2-D DP", 1463, 72.5],
  ["Best Time to Buy and Sell Stock IV", "Hard", "2-D DP", 188, 39.8],
  ["Best Time to Buy and Sell Stock III", "Hard", "2-D DP", 123, 45.8],

  // ===== Bit Manipulation =====
  ["Single Number", "Easy", "Bit Manipulation", 136, 72.5],
  ["Number of 1 Bits", "Easy", "Bit Manipulation", 191, 67.5],
  ["Counting Bits", "Easy", "Bit Manipulation", 338, 76.5],
  ["Reverse Bits", "Easy", "Bit Manipulation", 190, 55.5],
  ["Missing Number", "Easy", "Bit Manipulation", 268, 63.5],
  ["Sum of Two Integers", "Medium", "Bit Manipulation", 371, 51.5],
  ["Reverse Integer", "Medium", "Bit Manipulation", 7, 28.5],
  ["Add Binary", "Easy", "Bit Manipulation", 67, 52.5],
  ["Power of Two", "Easy", "Bit Manipulation", 231, 46.8],
  ["Bitwise AND of Numbers Range", "Medium", "Bit Manipulation", 201, 42.5],
  ["Single Number II", "Medium", "Bit Manipulation", 137, 60.5],
  ["Single Number III", "Medium", "Bit Manipulation", 260, 68.2],
  ["Minimum Bit Flips to Convert Number", "Easy", "Bit Manipulation", 2220, 83.5],

  // ===== Additional problems to reach ~600+ =====
  // More Arrays & Hashing
  ["Spiral Matrix III", "Medium", "Math & Geometry", 885, 74.5],
  ["Boats to Save People", "Medium", "Two Pointers", 881, 54.8],
  ["Container With Most Water", "Medium", "Two Pointers", 11, 55.5],
  ["Minimum Penalty for a Shop", "Medium", "Greedy", 2483, 56.5],
  ["Minimum Cost to Make All Characters Equal", "Medium", "Greedy", 2712, 48.5],
  ["Maximum Ice Cream Bars", "Medium", "Greedy", 1833, 65.2],

  // More Trees
  ["Range Sum of BST", "Easy", "Trees", 938, 86.5],
  ["Two Sum IV - Input is a BST", "Easy", "Trees", 653, 60.8],
  ["Increasing Order Search Tree", "Easy", "Trees", 897, 78.5],
  ["Search in a Binary Search Tree", "Easy", "Trees", 700, 78.2],
  ["Insert into a Binary Search Tree", "Easy", "Trees", 701, 74.5],
  ["Find Largest Value in Each Tree Row", "Medium", "Trees", 515, 65.8],
  ["Add One Row to Tree", "Medium", "Trees", 623, 55.2],
  ["Most Frequent Subtree Sum", "Medium", "Trees", 508, 65.5],
  ["Binary Tree Pruning", "Medium", "Trees", 814, 74.2],
  ["Distribute Coins in Binary Trees", "Medium", "Trees", 979, 73.5],
  ["Smallest String Starting From Leaf", "Medium", "Trees", 988, 50.2],
  ["Pseudo-Palindromic Paths in a Binary Tree", "Medium", "Trees", 1457, 69.2],
  ["Step-By-Step Directions From a Binary Tree Node to Another", "Medium", "Trees", 2096, 49.5],

  // More Graphs
  ["Time Needed to Inform All Employees", "Medium", "Graphs", 1376, 60.5],
  ["Possible Bipartition", "Medium", "Graphs", 886, 50.2],
  ["Find if Path Exists in Graph", "Easy", "Graphs", 1971, 52.5],
  ["Longest Path With Different Adjacent Characters", "Hard", "Graphs", 2246, 48.2],
  ["Number of Operations to Make Network Connected", "Medium", "Graphs", 1319, 61.2],
  ["Minimum Score of a Path Between Two Cities", "Medium", "Graphs", 2492, 44.2],
  ["Parallel Courses III", "Hard", "Graphs", 2050, 58.5],
  ["Checking Existence of Edge Length Limited Paths", "Hard", "Graphs", 1697, 52.8],

  // More 1-D DP
  ["Fibonacci Number", "Easy", "1-D DP", 509, 69.5],
  ["Maximum Length of Pair Chain", "Medium", "1-D DP", 646, 56.8],
  ["Uncrossed Lines", "Medium", "1-D DP", 1035, 60.5],
  ["Longest String Chain", "Medium", "1-D DP", 1048, 60.2],
  ["Number of Longest Increasing Subsequence", "Medium", "1-D DP", 673, 43.5],
  ["Profitable Schemes", "Hard", "1-D DP", 879, 47.8],
  ["Count Ways To Build Good Strings", "Medium", "1-D DP", 2466, 52.5],
  ["Best Team With No Conflicts", "Medium", "1-D DP", 1626, 49.2],
  ["Longest Arithmetic Subsequence", "Medium", "1-D DP", 1027, 50.5],
  ["Longest Arithmetic Subsequence of Given Difference", "Medium", "1-D DP", 1218, 52.8],

  // More Backtracking
  ["Generate Parentheses", "Medium", "Backtracking", 22, 74.2],
  ["Letter Combinations of a Phone Number", "Medium", "Backtracking", 17, 60.5],
  ["Combination Sum III", "Medium", "Backtracking", 216, 68.5],
  ["Beautiful Arrangement", "Medium", "Backtracking", 526, 65.8],
  ["Increasing Subsequences", "Medium", "Backtracking", 491, 55.2],
  ["All Paths From Source to Target", "Medium", "Backtracking", 797, 82.5],

  // More Binary Search
  ["Search Insert Position", "Easy", "Binary Search", 35, 42.2],
  ["Sqrt(x)", "Easy", "Binary Search", 69, 38.5],
  ["Peak Index in a Mountain Array", "Medium", "Binary Search", 852, 69.5],
  ["Maximum Number of Removable Characters", "Medium", "Binary Search", 1898, 39.8],
  ["Minimum Speed to Arrive on Time", "Medium", "Binary Search", 1870, 40.2],
  ["Find the Smallest Divisor Given a Threshold", "Medium", "Binary Search", 1283, 55.8],
  ["Kth Missing Positive Number", "Easy", "Binary Search", 1539, 58.2],

  // More Stack
  ["Next Greater Element I", "Easy", "Stack", 496, 72.5],
  ["Next Greater Element II", "Medium", "Stack", 503, 64.2],
  ["Trapping Rain Water", "Hard", "Stack", 42, 60.5],
  ["Basic Calculator", "Hard", "Stack", 224, 42.5],
  ["Basic Calculator II", "Medium", "Stack", 227, 43.2],
  ["Remove K Digits", "Medium", "Stack", 402, 33.5],
  ["Flatten Nested List Iterator", "Medium", "Stack", 341, 64.5],
  ["Sum of Subarray Minimums", "Medium", "Stack", 907, 37.2],
  ["Number of Visible People in a Queue", "Hard", "Stack", 1944, 72.5],

  // More Heap
  ["Sort Characters By Frequency", "Medium", "Heap / Priority Queue", 451, 70.5],
  ["Maximum Product of Two Elements in an Array", "Easy", "Heap / Priority Queue", 1464, 80.2],
  ["Relative Ranks", "Easy", "Heap / Priority Queue", 506, 59.5],
  ["Merge k Sorted Lists", "Hard", "Heap / Priority Queue", 23, 52.5],
  ["Smallest Range Covering Elements from K Lists", "Hard", "Heap / Priority Queue", 632, 62.5],
  ["Trapping Rain Water II", "Hard", "Heap / Priority Queue", 407, 47.5],

  // More Intervals
  ["Interval List Intersections", "Medium", "Intervals", 986, 72.5],
  ["Car Pooling", "Medium", "Intervals", 1094, 58.8],
  ["Data Stream as Disjoint Intervals", "Hard", "Intervals", 352, 53.5],

  // More Advanced Graphs
  ["Course Schedule IV", "Medium", "Advanced Graphs", 1462, 49.2],
  ["Shortest Path Visiting All Nodes", "Hard", "Advanced Graphs", 847, 65.8],
  ["Number of Ways to Arrive at Destination", "Medium", "Advanced Graphs", 1976, 35.5],
  ["Word Ladder II", "Hard", "Advanced Graphs", 126, 27.5],

  // More Math & Geometry
  ["Game of Life", "Medium", "Math & Geometry", 289, 68.5],
  ["Robot Return to Origin", "Easy", "Math & Geometry", 657, 76.5],
  ["Water and Jug Problem", "Medium", "Math & Geometry", 365, 36.2],
  ["Basic Calculator", "Hard", "Math & Geometry", 224, 42.5],
  ["Max Points on a Line", "Hard", "Math & Geometry", 149, 24.5],
  ["Minimum Moves to Equal Array Elements", "Medium", "Math & Geometry", 453, 55.2],
  ["Minimum Moves to Equal Array Elements II", "Medium", "Math & Geometry", 462, 60.2],
  ["Shift 2D Grid", "Easy", "Math & Geometry", 1260, 68.5],
  ["Ugly Number", "Easy", "Math & Geometry", 263, 42.8],
  ["String to Integer (atoi)", "Medium", "Math & Geometry", 8, 16.8],
  ["Zigzag Conversion", "Medium", "Math & Geometry", 6, 46.5],

  // More 2-D DP
  ["Longest Palindromic Subsequence", "Medium", "2-D DP", 516, 62.5],
  ["Count Square Submatrices with All Ones", "Medium", "2-D DP", 1277, 76.2],
  ["Triangle", "Medium", "2-D DP", 120, 55.8],
  ["Minimum Falling Path Sum", "Medium", "2-D DP", 931, 65.5],
  ["Minimum Falling Path Sum II", "Hard", "2-D DP", 1289, 62.8],
  ["Paint House", "Medium", "2-D DP", 256, 59.5],
  ["Paint House II", "Hard", "2-D DP", 265, 52.5],
  ["Decode Ways II", "Hard", "2-D DP", 639, 30.2],
  ["Minimum ASCII Delete Sum of Two Strings", "Medium", "2-D DP", 712, 65.5],
  ["Shortest Common Supersequence", "Hard", "2-D DP", 1092, 58.5],
  ["Freedom Trail", "Hard", "2-D DP", 514, 38.2],
  ["Scramble String", "Hard", "2-D DP", 87, 38.8],

  // More Bit Manipulation
  ["Hamming Distance", "Easy", "Bit Manipulation", 461, 75.5],
  ["Subsets", "Medium", "Bit Manipulation", 78, 76.5],
  ["UTF-8 Validation", "Medium", "Bit Manipulation", 393, 45.2],
  ["Maximum XOR of Two Numbers in an Array", "Medium", "Bit Manipulation", 421, 54.5],
  ["Find the Longest Substring Containing Vowels in Even Counts", "Medium", "Bit Manipulation", 1371, 54.8],
  ["Total Hamming Distance", "Medium", "Bit Manipulation", 477, 52.5],
  ["Decode XORed Array", "Easy", "Bit Manipulation", 1720, 86.2],
  ["XOR Queries of a Subarray", "Medium", "Bit Manipulation", 1310, 73.5],

  // More Sliding Window
  ["Grumpy Bookstore Owner", "Medium", "Sliding Window", 1052, 58.5],
  ["Maximum Points You Can Obtain from Cards", "Medium", "Sliding Window", 1423, 53.5],
  ["Get Equal Substrings Within Budget", "Medium", "Sliding Window", 1208, 49.2],
  ["Find All Anagrams in a String", "Medium", "Sliding Window", 438, 50.2],
  ["Max Consecutive Ones III", "Medium", "Sliding Window", 1004, 64.5],
  ["Subarrays with K Different Integers", "Hard", "Sliding Window", 992, 56.2],
  ["Shortest Subarray with Sum at Least K", "Hard", "Sliding Window", 862, 27.5],

  // More Linked List
  ["Delete Node in a Linked List", "Medium", "Linked List", 237, 76.5],
  ["Linked List Cycle II", "Medium", "Linked List", 142, 49.5],
  ["Next Greater Node In Linked List", "Medium", "Linked List", 1019, 60.2],
  ["Split Linked List in Parts", "Medium", "Linked List", 725, 58.5],
  ["Swapping Nodes in a Linked List", "Medium", "Linked List", 1721, 68.5],
  ["Add Two Numbers II", "Medium", "Linked List", 445, 60.2],

  // More Tries
  ["Longest Word in Dictionary", "Medium", "Tries", 720, 52.5],
  ["Maximum XOR of Two Numbers in an Array", "Medium", "Tries", 421, 54.5],
  ["Palindrome Pairs", "Hard", "Tries", 336, 35.8],
  ["Stream of Characters", "Hard", "Tries", 1032, 52.5],

  // Additional miscellaneous to push toward 800+
  ["Minimum Window Substring", "Hard", "Sliding Window", 76, 41.0],
  ["Wildcard Matching", "Hard", "2-D DP", 44, 27.5],
  ["Word Break II", "Hard", "Backtracking", 140, 46.2],
  ["Concatenated Words", "Hard", "1-D DP", 472, 46.5],
  ["Frog Jump", "Hard", "1-D DP", 403, 43.8],
  ["Strange Printer", "Hard", "2-D DP", 664, 48.2],
  ["Super Egg Drop", "Hard", "2-D DP", 887, 27.5],
  ["Tallest Billboard", "Hard", "2-D DP", 956, 40.5],
  ["Student Attendance Record II", "Hard", "1-D DP", 552, 42.5],
  ["Minimum Difficulty of a Job Schedule", "Hard", "1-D DP", 1335, 58.2],
  ["Word Search II", "Hard", "Tries", 212, 36.5],
  ["Sliding Window Median", "Hard", "Sliding Window", 480, 42.5],
  ["Minimum Number of Refueling Stops", "Hard", "Heap / Priority Queue", 871, 39.8],
  ["The Skyline Problem", "Hard", "Heap / Priority Queue", 218, 42.5],
  ["Course Schedule III", "Hard", "Greedy", 630, 35.8],
  ["Minimum Cost to Hire K Workers", "Hard", "Heap / Priority Queue", 857, 52.5],
  ["Stamping The Sequence", "Hard", "Greedy", 936, 62.5],
  ["Minimum Replacements to Sort the Array", "Hard", "Greedy", 2366, 44.2],
  ["Patching Array", "Hard", "Greedy", 330, 40.5],
  ["Minimum Number of Taps to Open to Water a Garden", "Hard", "Greedy", 1326, 49.5],
  ["Longest Duplicate Substring", "Hard", "Binary Search", 1044, 30.5],
  ["Russian Doll Envelopes", "Hard", "Binary Search", 354, 39.8],
  ["K-th Smallest in Lexicographical Order", "Hard", "Tries", 440, 32.5],
  ["Prefix and Suffix Search", "Hard", "Tries", 745, 41.5],
  ["Number of Digit One", "Hard", "Math & Geometry", 233, 34.5],
  ["Count of Range Sum", "Hard", "Binary Search", 327, 36.8],
  ["Minimum Cost to Merge Stones", "Hard", "2-D DP", 1000, 42.5],
  ["Minimum Insertion Steps to Make a String Palindrome", "Hard", "2-D DP", 1312, 67.5],
  ["Number of Music Playlists", "Hard", "1-D DP", 920, 50.5],
  ["Count Different Palindromic Subsequences", "Hard", "2-D DP", 730, 45.5],
  ["Smallest Sufficient Team", "Hard", "2-D DP", 1125, 50.2],
  ["Critical Connections in a Network", "Hard", "Graphs", 1192, 56.2],
  ["Alien Dictionary", "Hard", "Graphs", 269, 35.5],
  ["Binary Tree Maximum Path Sum", "Hard", "Trees", 124, 39.5],
  ["Serialize and Deserialize Binary Tree", "Hard", "Trees", 297, 55.5],
  ["Data Stream as Disjoint Intervals", "Hard", "Intervals", 352, 53.5],
  ["Employee Free Time", "Hard", "Intervals", 759, 72.5],

  // Fill remaining to get closer to 700+
  ["Valid Number", "Hard", "Math & Geometry", 65, 19.5],
  ["N-Queens", "Hard", "Backtracking", 51, 65.5],
  ["Sudoku Solver", "Hard", "Backtracking", 37, 58.2],
  ["Expression Add Operators", "Hard", "Backtracking", 282, 40.2],
  ["Remove Invalid Parentheses", "Hard", "Backtracking", 301, 47.8],
  ["24 Game", "Hard", "Backtracking", 679, 49.5],
  ["Stickers to Spell Word", "Hard", "Backtracking", 691, 48.5],
  ["Largest Component Size by Common Factor", "Hard", "Graphs", 952, 40.5],
  ["Swim in Rising Water", "Hard", "Graphs", 778, 61.5],
  ["Bus Routes", "Hard", "Graphs", 815, 47.5],
  ["Similar String Groups", "Hard", "Graphs", 839, 48.2],
  ["Minimize Malware Spread", "Hard", "Graphs", 924, 42.5],
  ["Regions Cut By Slashes", "Medium", "Graphs", 959, 70.5],
  ["Satisfiability of Equality Equations", "Medium", "Graphs", 990, 51.2],
  ["Flower Planting With No Adjacent", "Medium", "Graphs", 1042, 50.8],
  ["Smallest String With Swaps", "Medium", "Graphs", 1202, 57.5],
  ["Sort Items by Groups Respecting Dependencies", "Hard", "Graphs", 1203, 51.2],
  ["Reconstruct Itinerary", "Hard", "Graphs", 332, 42.5],
  ["Strongly Connected Components", "Hard", "Advanced Graphs", 0, 50.0],
  ["Topological Sort", "Medium", "Advanced Graphs", 0, 55.0],

  // More 1-D DP to round out
  ["Paint Fence", "Medium", "1-D DP", 276, 44.5],
  ["Wiggle Subsequence", "Medium", "1-D DP", 376, 48.2],
  ["Largest Divisible Subset", "Medium", "1-D DP", 368, 42.5],
  ["Predict the Winner", "Medium", "1-D DP", 486, 52.8],
  ["Shopping Offers", "Medium", "1-D DP", 638, 55.2],
  ["2 Keys Keyboard", "Medium", "1-D DP", 650, 53.5],
  ["Cheapest Flights Within K Stops", "Medium", "1-D DP", 787, 40.5],
  ["Where Will the Ball Fall", "Medium", "1-D DP", 1706, 70.5],
  ["Number of Ways to Form a Target String Given a Dictionary", "Hard", "1-D DP", 1639, 45.2],
  ["Tallest Billboard", "Hard", "1-D DP", 956, 40.5],

  // Extra problems for breadth
  ["Range Sum Query - Mutable", "Medium", "Arrays & Hashing", 307, 40.8],
  ["Count of Smaller Numbers After Self", "Hard", "Arrays & Hashing", 315, 42.5],
  ["The Number of Weak Characters in the Game", "Medium", "Arrays & Hashing", 1996, 45.2],
  ["Queue Reconstruction by Height", "Medium", "Greedy", 406, 72.5],
  ["Non-decreasing Array", "Medium", "Greedy", 665, 23.5],
  ["Task Scheduler", "Medium", "Greedy", 621, 58.5],
  ["Lemonade Change", "Easy", "Greedy", 860, 53.5],
  ["Score After Flipping Matrix", "Medium", "Greedy", 861, 75.5],
  ["Broken Calculator", "Medium", "Greedy", 991, 54.5],
  ["String Without AAA or BBB", "Medium", "Greedy", 984, 43.2],
  ["Minimize Maximum of Array", "Medium", "Greedy", 2439, 34.5],
  ["Minimum Amount of Time to Fill Cups", "Easy", "Greedy", 2335, 57.5],

  // More Binary Search
  ["H-Index II", "Medium", "Binary Search", 275, 37.5],
  ["Count Negative Numbers in a Sorted Matrix", "Easy", "Binary Search", 1351, 77.5],
  ["Fair Distribution of Cookies", "Medium", "Binary Search", 2305, 65.8],
  ["Minimum Limit of Balls in a Bag", "Medium", "Binary Search", 1760, 61.2],
  ["Magnetic Force Between Two Balls", "Medium", "Binary Search", 1552, 58.5],
  ["Maximum Running Time of N Computers", "Hard", "Binary Search", 2141, 42.5],
  ["Minimize the Maximum Difference of Pairs", "Medium", "Binary Search", 2616, 47.5],

  // More Stack
  ["Largest Rectangle in Histogram", "Hard", "Stack", 84, 43.5],
  ["Maximal Rectangle", "Hard", "Stack", 85, 47.2],
  ["Minimum Remove to Make Valid Parentheses", "Medium", "Stack", 1249, 67.5],
  ["Maximum Nesting Depth of the Parentheses", "Easy", "Stack", 1614, 83.5],
  ["Build an Array With Stack Operations", "Medium", "Stack", 1441, 82.5],
  ["Make The String Great", "Easy", "Stack", 1544, 73.5],
  ["Crawler Log Folder", "Easy", "Stack", 1598, 65.2],

  // Remaining to push past 800+
  ["Reverse String", "Easy", "Two Pointers", 344, 77.2],
  ["Reverse String II", "Easy", "Two Pointers", 541, 50.8],
  ["Backspace String Compare", "Easy", "Two Pointers", 844, 47.5],
  ["Sort Array By Parity", "Easy", "Two Pointers", 905, 75.5],
  ["Sort Array By Parity II", "Easy", "Two Pointers", 922, 71.2],
  ["Long Pressed Name", "Easy", "Two Pointers", 925, 35.5],
  ["Intersection of Two Arrays", "Easy", "Two Pointers", 349, 72.5],
  ["Intersection of Two Arrays II", "Easy", "Two Pointers", 350, 56.5],
  ["Is Subsequence", "Easy", "Two Pointers", 392, 48.5],

  // Fill to ~850+
  ["Maximum Erasure Value", "Medium", "Sliding Window", 1695, 57.5],
  ["Minimum Operations to Reduce X to Zero", "Medium", "Sliding Window", 1658, 37.5],
  ["Number of Substrings Containing All Three Characters", "Medium", "Sliding Window", 1358, 64.5],
  ["Replace the Substring for Balanced String", "Medium", "Sliding Window", 1234, 37.5],
  ["Binary Subarrays With Sum", "Medium", "Sliding Window", 930, 52.5],
  ["Minimum Swaps to Group All 1's Together II", "Medium", "Sliding Window", 2134, 55.2],

  // More to fill
  ["Rotate String", "Easy", "Arrays & Hashing", 796, 55.8],
  ["Isomorphic Strings", "Easy", "Arrays & Hashing", 205, 43.5],
  ["Jewels and Stones", "Easy", "Arrays & Hashing", 771, 88.5],
  ["Number of Good Pairs", "Easy", "Arrays & Hashing", 1512, 88.2],
  ["How Many Numbers Are Smaller Than the Current Number", "Easy", "Arrays & Hashing", 1365, 86.5],
  ["Unique Number of Occurrences", "Easy", "Arrays & Hashing", 1207, 74.8],
  ["Count Number of Pairs With Absolute Difference K", "Easy", "Arrays & Hashing", 2006, 83.5],
  ["Find All Duplicates in an Array", "Medium", "Arrays & Hashing", 442, 73.5],
  ["Kth Distinct String in an Array", "Easy", "Arrays & Hashing", 2053, 73.2],
  ["Check if Every Row and Column Contains All Numbers", "Easy", "Arrays & Hashing", 2133, 53.5],
  ["Find Players With Zero or One Losses", "Medium", "Arrays & Hashing", 2225, 70.2],
  ["Equal Row and Column Pairs", "Medium", "Arrays & Hashing", 2352, 71.8],
  ["Determine if Two Strings Are Close", "Medium", "Arrays & Hashing", 1657, 55.5],
  ["Largest Number", "Medium", "Arrays & Hashing", 179, 34.8],
  ["Minimum Rounds to Complete All Tasks", "Medium", "Arrays & Hashing", 2244, 60.5],
  ["Task Scheduler", "Medium", "Arrays & Hashing", 621, 58.5],
  ["Monotone Increasing Digits", "Medium", "Arrays & Hashing", 738, 47.5],
  ["Top K Frequent Words", "Medium", "Arrays & Hashing", 692, 57.8],
  ["Sort Characters By Frequency", "Medium", "Arrays & Hashing", 451, 70.5],
  ["Find the Difference of Two Arrays", "Easy", "Arrays & Hashing", 2215, 70.2],
  ["Minimum Index Sum of Two Lists", "Easy", "Arrays & Hashing", 599, 54.5],

  // Extra Hard problems
  ["Trapping Rain Water", "Hard", "Arrays & Hashing", 42, 60.5],
  ["Median of Two Sorted Arrays", "Hard", "Arrays & Hashing", 4, 39.5],
  ["Merge k Sorted Lists", "Hard", "Arrays & Hashing", 23, 52.5],
  ["Longest Valid Parentheses", "Hard", "Stack", 32, 33.5],
  ["Minimum Window Substring", "Hard", "Arrays & Hashing", 76, 41.0],
  ["Maximal Rectangle", "Hard", "Arrays & Hashing", 85, 47.2],
  ["Interleaving String", "Hard", "2-D DP", 97, 37.5],
  ["Binary Tree Maximum Path Sum", "Hard", "Trees", 124, 39.5],

  // ===== BATCH 2: Additional ~300 problems to reach ~954 =====

  // More Arrays & Hashing
  ["Concatenation of Array", "Easy", "Arrays & Hashing", 1929, 91.5],
  ["Running Sum of 1d Array", "Easy", "Arrays & Hashing", 1480, 89.2],
  ["Richest Customer Wealth", "Easy", "Arrays & Hashing", 1672, 88.5],
  ["Shuffle the Array", "Easy", "Arrays & Hashing", 1470, 88.2],
  ["Kids With the Greatest Number of Candies", "Easy", "Arrays & Hashing", 1431, 88.0],
  ["Decompress Run-Length Encoded List", "Easy", "Arrays & Hashing", 1313, 86.5],
  ["Create Target Array in the Given Order", "Easy", "Arrays & Hashing", 1389, 85.8],
  ["XOR Operation in an Array", "Easy", "Arrays & Hashing", 1486, 84.2],
  ["Sum of All Odd Length Subarrays", "Easy", "Arrays & Hashing", 1588, 83.5],
  ["Final Value of Variable After Performing Operations", "Easy", "Arrays & Hashing", 2011, 89.2],
  ["Defanging an IP Address", "Easy", "Arrays & Hashing", 1108, 89.5],
  ["Maximum Number of Words Found in Sentences", "Easy", "Arrays & Hashing", 2114, 88.2],
  ["Goal Parser Interpretation", "Easy", "Arrays & Hashing", 1678, 86.5],
  ["Count Items Matching a Rule", "Easy", "Arrays & Hashing", 1773, 84.8],
  ["Smallest Index With Equal Value", "Easy", "Arrays & Hashing", 2057, 73.2],
  ["Check If Two String Arrays are Equivalent", "Easy", "Arrays & Hashing", 1662, 82.5],
  ["Truncate Sentence", "Easy", "Arrays & Hashing", 1816, 81.5],
  ["Count the Number of Consistent Strings", "Easy", "Arrays & Hashing", 1684, 82.2],
  ["Decode the Message", "Easy", "Arrays & Hashing", 2325, 85.5],
  ["Find Target Indices After Sorting Array", "Easy", "Arrays & Hashing", 2089, 78.5],
  ["Number of Arithmetic Triplets", "Easy", "Arrays & Hashing", 2367, 84.2],
  ["Maximum Count of Positive Integer and Negative Integer", "Easy", "Arrays & Hashing", 2529, 78.5],
  ["Left and Right Sum Differences", "Easy", "Arrays & Hashing", 2574, 87.5],
  ["Find the Highest Altitude", "Easy", "Arrays & Hashing", 1732, 79.2],
  ["Find Common Characters", "Easy", "Arrays & Hashing", 1002, 68.5],

  // More Two Pointers
  ["Reverse Vowels of a String", "Easy", "Two Pointers", 345, 52.5],
  ["Flipping an Image", "Easy", "Two Pointers", 832, 80.5],
  ["Di String Match", "Easy", "Two Pointers", 942, 77.5],
  ["Minimum Difference Between Highest and Lowest of K Scores", "Easy", "Two Pointers", 1984, 54.8],
  ["Two Sum II - Input Array Is Sorted", "Medium", "Two Pointers", 167, 61.5],
  ["Partition Array According to Given Pivot", "Medium", "Two Pointers", 2161, 86.2],
  ["Minimize Maximum Pair Sum in Array", "Medium", "Two Pointers", 1877, 80.5],

  // More Sliding Window
  ["Contains Duplicate II", "Easy", "Sliding Window", 219, 44.5],
  ["Minimum Difference Between Highest and Lowest of K Scores", "Easy", "Sliding Window", 1984, 54.8],
  ["Diet Plan Performance", "Easy", "Sliding Window", 1176, 53.2],
  ["Defuse the Bomb", "Easy", "Sliding Window", 1652, 62.5],
  ["Maximum Average Subarray I", "Easy", "Sliding Window", 643, 45.2],
  ["Longest Nice Subarray", "Medium", "Sliding Window", 2401, 52.5],
  ["Maximum Sum of Distinct Subarrays With Length K", "Medium", "Sliding Window", 2461, 35.8],
  ["Count Subarrays Where Max Element Appears at Least K Times", "Medium", "Sliding Window", 2962, 44.5],
  ["Minimum Recolors to Get K Consecutive Black Blocks", "Easy", "Sliding Window", 2379, 58.5],
  ["Find the K-Beauty of a Number", "Easy", "Sliding Window", 2269, 70.2],

  // More Stack
  ["Final Prices With a Special Discount in a Shop", "Easy", "Stack", 1475, 77.5],
  ["Backspace String Compare", "Easy", "Stack", 844, 47.5],
  ["Remove Outermost Parentheses", "Easy", "Stack", 1021, 81.2],
  ["Maximum Nesting Depth of the Parentheses", "Easy", "Stack", 1614, 83.5],
  ["Remove All Adjacent Duplicates In String", "Easy", "Stack", 1047, 70.5],
  ["Daily Temperatures", "Medium", "Stack", 739, 66.5],
  ["Minimum String Length After Removing Substrings", "Easy", "Stack", 2696, 73.2],
  ["Clear Digits", "Easy", "Stack", 3174, 79.5],
  ["Number of Students Unable to Eat Lunch", "Easy", "Stack", 1700, 72.5],
  ["Time Needed to Buy Tickets", "Easy", "Stack", 2073, 64.5],

  // More Binary Search
  ["Arranging Coins", "Easy", "Binary Search", 441, 46.2],
  ["Valid Perfect Square", "Easy", "Binary Search", 367, 43.8],
  ["Find Smallest Letter Greater Than Target", "Easy", "Binary Search", 744, 44.5],
  ["Count Negative Numbers in a Sorted Matrix", "Easy", "Binary Search", 1351, 77.5],
  ["Check If N and Its Double Exist", "Easy", "Binary Search", 1346, 37.5],
  ["Special Array With X Elements Greater Than or Equal X", "Easy", "Binary Search", 1608, 60.5],
  ["Maximum Count of Positive Integer and Negative Integer", "Easy", "Binary Search", 2529, 78.5],
  ["Search a 2D Matrix II", "Medium", "Binary Search", 240, 52.5],
  ["Find Right Interval", "Medium", "Binary Search", 436, 51.2],
  ["Random Pick with Weight", "Medium", "Binary Search", 528, 46.5],

  // More Linked List
  ["Convert Binary Number in a Linked List to Integer", "Easy", "Linked List", 1290, 82.5],
  ["Merge In Between Linked Lists", "Medium", "Linked List", 1669, 74.5],
  ["Remove Zero Sum Consecutive Nodes from Linked List", "Medium", "Linked List", 1171, 44.5],
  ["Insert into a Sorted Circular Linked List", "Medium", "Linked List", 708, 35.2],
  ["Linked List Random Node", "Medium", "Linked List", 382, 62.5],
  ["Plus One Linked List", "Medium", "Linked List", 369, 62.2],
  ["Delete the Middle Node of a Linked List", "Medium", "Linked List", 2095, 58.2],
  ["Find the Minimum and Maximum Number of Nodes Between Critical Points", "Medium", "Linked List", 2058, 58.5],
  ["Remove Linked List Elements", "Easy", "Linked List", 203, 47.5],
  ["Reverse Linked List", "Easy", "Linked List", 206, 75.5],

  // More Trees
  ["Merge Two Binary Trees", "Easy", "Trees", 617, 78.5],
  ["Maximum Depth of N-ary Tree", "Easy", "Trees", 559, 72.5],
  ["N-ary Tree Preorder Traversal", "Easy", "Trees", 589, 77.2],
  ["N-ary Tree Postorder Traversal", "Easy", "Trees", 590, 77.5],
  ["Binary Tree Paths", "Easy", "Trees", 257, 62.5],
  ["Find Mode in Binary Search Tree", "Easy", "Trees", 501, 48.8],
  ["Second Minimum Node In a Binary Tree", "Easy", "Trees", 671, 44.2],
  ["Longest Univalue Path", "Medium", "Trees", 687, 40.2],
  ["Flip Equivalent Binary Trees", "Medium", "Trees", 951, 67.2],
  ["Sum of Nodes with Even-Valued Grandparent", "Medium", "Trees", 1315, 85.8],
  ["Deepest Leaves Sum", "Medium", "Trees", 1302, 85.5],
  ["Smallest String Starting From Leaf", "Medium", "Trees", 988, 50.2],
  ["Delete Leaves With a Given Value", "Medium", "Trees", 1325, 75.5],
  ["Number of Good Leaf Nodes Pairs", "Medium", "Trees", 1530, 63.2],
  ["Linked List in Binary Tree", "Medium", "Trees", 1367, 44.5],
  ["Complete Binary Tree Inserter", "Medium", "Trees", 919, 65.8],
  ["All Elements in Two Binary Search Trees", "Medium", "Trees", 1305, 80.2],
  ["Construct Binary Search Tree from Preorder Traversal", "Medium", "Trees", 1008, 81.5],
  ["Flatten Nested List Iterator", "Medium", "Trees", 341, 64.5],
  ["Insufficient Nodes in Root to Leaf Paths", "Medium", "Trees", 1080, 53.2],

  // More Tries
  ["Sum of Prefix Scores of Strings", "Hard", "Tries", 2416, 47.5],
  ["Count Pairs With XOR in a Range", "Hard", "Tries", 1803, 48.2],
  ["Design Search Autocomplete System", "Hard", "Tries", 642, 49.5],
  ["Word Squares", "Hard", "Tries", 425, 52.8],
  ["Lexicographical Numbers", "Medium", "Tries", 386, 60.5],

  // More Heap / Priority Queue
  ["Kth Largest Element in a Stream", "Easy", "Heap / Priority Queue", 703, 56.5],
  ["Minimum Cost to Connect Sticks", "Medium", "Heap / Priority Queue", 1167, 67.5],
  ["Furthest Building You Can Reach", "Medium", "Heap / Priority Queue", 1642, 47.5],
  ["Reduce Array Size to The Half", "Medium", "Heap / Priority Queue", 1338, 69.5],
  ["Remove Stones to Minimize the Total", "Medium", "Heap / Priority Queue", 1962, 66.5],
  ["Maximal Score After Applying K Operations", "Medium", "Heap / Priority Queue", 2530, 55.2],
  ["Top K Frequent Elements", "Medium", "Heap / Priority Queue", 347, 64.2],
  ["Last Stone Weight", "Easy", "Heap / Priority Queue", 1046, 65.5],
  ["Minimum Number of Refueling Stops", "Hard", "Heap / Priority Queue", 871, 39.8],
  ["Sliding Window Median", "Hard", "Heap / Priority Queue", 480, 42.5],

  // More Backtracking
  ["Binary Watch", "Easy", "Backtracking", 401, 52.5],
  ["Letter Tile Possibilities", "Medium", "Backtracking", 1079, 76.2],
  ["Path with Maximum Gold", "Medium", "Backtracking", 1219, 67.5],
  ["Unique Paths III", "Hard", "Backtracking", 980, 82.2],
  ["Count Number of Maximum Bitwise-OR Subsets", "Medium", "Backtracking", 2044, 77.5],
  ["Fair Distribution of Cookies", "Medium", "Backtracking", 2305, 65.8],
  ["Construct Smallest Number From DI String", "Medium", "Backtracking", 2375, 76.5],
  ["Non-decreasing Subsequences", "Medium", "Backtracking", 491, 58.0],
  ["Iterator for Combination", "Medium", "Backtracking", 1286, 74.5],
  ["Sequential Digits", "Medium", "Backtracking", 1291, 63.2],

  // More Graphs
  ["Find the Town Judge", "Easy", "Graphs", 997, 50.2],
  ["Find Center of Star Graph", "Easy", "Graphs", 1791, 84.2],
  ["Find if Path Exists in Graph", "Easy", "Graphs", 1971, 52.5],
  ["Island Perimeter", "Easy", "Graphs", 463, 70.5],
  ["Flood Fill", "Easy", "Graphs", 733, 61.5],
  ["Longest Cycle in a Graph", "Hard", "Graphs", 2360, 40.5],
  ["Minimum Time to Collect All Apples in a Tree", "Medium", "Graphs", 1443, 57.2],
  ["Path With Minimum Effort", "Medium", "Graphs", 1631, 55.8],
  ["Minimum Genetic Mutation", "Medium", "Graphs", 433, 50.2],
  ["Network Delay Time", "Medium", "Graphs", 743, 52.5],
  ["Course Schedule IV", "Medium", "Graphs", 1462, 49.2],
  ["Maximal Network Rank", "Medium", "Graphs", 1615, 60.5],
  ["Find All Groups of Farmland", "Medium", "Graphs", 1992, 68.5],
  ["Minimum Fuel Cost to Report to the Capital", "Medium", "Graphs", 2477, 61.5],
  ["Most Stones Removed with Same Row or Column", "Medium", "Graphs", 947, 58.5],

  // More 1-D DP
  ["Is Subsequence", "Easy", "1-D DP", 392, 48.5],
  ["Best Time to Buy and Sell Stock", "Easy", "1-D DP", 121, 54.2],
  ["Divisor Game", "Easy", "1-D DP", 1025, 67.5],
  ["Range Sum Query - Immutable", "Easy", "1-D DP", 303, 59.8],
  ["Get Maximum in Generated Array", "Easy", "1-D DP", 1646, 51.2],
  ["Min Cost to Climb Stairs", "Easy", "1-D DP", 746, 64.5],
  ["Extra Characters in a String", "Medium", "1-D DP", 2707, 52.2],
  ["Longest Palindromic Subsequence", "Medium", "1-D DP", 516, 62.5],
  ["Minimum Cost For Tickets", "Medium", "1-D DP", 983, 65.8],
  ["Count Square Submatrices with All Ones", "Medium", "1-D DP", 1277, 76.2],
  ["Unique Binary Search Trees", "Medium", "1-D DP", 96, 60.5],
  ["Maximize the Profit as the Salesman", "Medium", "1-D DP", 2830, 42.5],
  ["Count Number of Texts", "Medium", "1-D DP", 2266, 48.5],
  ["Stone Game VII", "Medium", "1-D DP", 1690, 60.2],
  ["Minimum Swaps To Make Sequences Increasing", "Hard", "1-D DP", 801, 40.5],

  // More Intervals
  ["Summary Ranges", "Easy", "Intervals", 228, 48.5],
  ["Teemo Attacking", "Easy", "Intervals", 495, 57.2],
  ["Determine if Two Events Have Conflict", "Easy", "Intervals", 2446, 50.5],
  ["Video Stitching", "Medium", "Intervals", 1024, 50.5],
  ["Divide Intervals Into Minimum Number of Groups", "Medium", "Intervals", 2406, 48.5],

  // More Greedy
  ["Lemonade Change", "Easy", "Greedy", 860, 53.5],
  ["Assign Cookies", "Easy", "Greedy", 455, 50.8],
  ["Maximum Units on a Truck", "Easy", "Greedy", 1710, 74.5],
  ["Array Partition", "Easy", "Greedy", 561, 77.5],
  ["Minimum Number of Moves to Seat Everyone", "Easy", "Greedy", 2037, 83.2],
  ["Maximum 69 Number", "Easy", "Greedy", 1323, 79.5],
  ["Split a String in Balanced Strings", "Easy", "Greedy", 1221, 85.5],
  ["Reduce Array Size to The Half", "Medium", "Greedy", 1338, 69.5],
  ["Maximum Number of Coins You Can Get", "Medium", "Greedy", 1561, 79.5],
  ["Advantage Shuffle", "Medium", "Greedy", 870, 51.5],
  ["Bag of Tokens", "Medium", "Greedy", 948, 52.5],
  ["Boats to Save People", "Medium", "Greedy", 881, 54.8],
  ["Minimum Deletions to Make String Balanced", "Medium", "Greedy", 1653, 58.5],
  ["Removing Minimum and Maximum From Array", "Medium", "Greedy", 2091, 60.2],
  ["Put Marbles in Bags", "Hard", "Greedy", 2551, 68.5],

  // More Advanced Graphs
  ["Connecting Cities With Minimum Cost", "Medium", "Advanced Graphs", 1135, 63.5],
  ["Optimize Water Distribution in a Village", "Hard", "Advanced Graphs", 1168, 64.2],
  ["Reachable Nodes In Subdivided Graph", "Hard", "Advanced Graphs", 882, 50.5],
  ["Minimum Obstacle Removal to Reach Corner", "Hard", "Advanced Graphs", 2290, 50.2],
  ["Second Minimum Time to Reach Destination", "Hard", "Advanced Graphs", 2045, 42.5],

  // More Math & Geometry
  ["Add Digits", "Easy", "Math & Geometry", 258, 63.5],
  ["Power of Three", "Easy", "Math & Geometry", 326, 45.2],
  ["Power of Four", "Easy", "Math & Geometry", 342, 47.5],
  ["Missing Number", "Easy", "Math & Geometry", 268, 63.5],
  ["Self Dividing Numbers", "Easy", "Math & Geometry", 728, 77.5],
  ["Base 7", "Easy", "Math & Geometry", 504, 48.8],
  ["Nim Game", "Easy", "Math & Geometry", 292, 56.2],
  ["Distribute Candies", "Easy", "Math & Geometry", 575, 66.5],
  ["Smallest Even Multiple", "Easy", "Math & Geometry", 2413, 87.5],
  ["Kth Factor of n", "Medium", "Math & Geometry", 1492, 63.2],
  ["Angle Between Hands of a Clock", "Medium", "Math & Geometry", 1344, 63.8],
  ["Minimum Time Difference", "Medium", "Math & Geometry", 539, 56.2],
  ["Rectangle Area", "Medium", "Math & Geometry", 223, 45.5],
  ["Mirror Reflection", "Medium", "Math & Geometry", 858, 63.2],
  ["Maximum Swap", "Medium", "Math & Geometry", 670, 48.5],
  ["Largest Perimeter Triangle", "Easy", "Math & Geometry", 976, 56.2],

  // More 2-D DP
  ["Maximal Square", "Medium", "2-D DP", 221, 45.2],
  ["Minimum Path Sum", "Medium", "2-D DP", 64, 63.8],
  ["Maximum Profit in Job Scheduling", "Hard", "2-D DP", 1235, 53.5],
  ["Palindrome Partitioning II", "Hard", "2-D DP", 132, 34.5],
  ["Minimum Cost to Cut a Stick", "Hard", "2-D DP", 1547, 58.2],
  ["Strange Printer", "Hard", "2-D DP", 664, 48.2],
  ["Minimum Score Triangulation of Polygon", "Medium", "2-D DP", 1039, 55.2],
  ["Maximum Length of Repeated Subarray", "Medium", "2-D DP", 718, 51.5],
  ["Uncrossed Lines", "Medium", "2-D DP", 1035, 60.5],
  ["Palindrome Removal", "Hard", "2-D DP", 1246, 46.5],

  // More Bit Manipulation
  ["Number Complement", "Easy", "Bit Manipulation", 476, 67.5],
  ["Binary Number with Alternating Bits", "Easy", "Bit Manipulation", 693, 61.5],
  ["Prime Number of Set Bits in Binary Representation", "Easy", "Bit Manipulation", 762, 68.2],
  ["Sort Integers by The Number of 1 Bits", "Easy", "Bit Manipulation", 1356, 73.5],
  ["Complement of Base 10 Integer", "Easy", "Bit Manipulation", 1009, 63.2],
  ["Convert a Number to Hexadecimal", "Easy", "Bit Manipulation", 405, 46.5],
  ["Binary Gap", "Easy", "Bit Manipulation", 868, 62.5],
  ["Divide Two Integers", "Medium", "Bit Manipulation", 29, 17.5],
  ["Gray Code", "Medium", "Bit Manipulation", 89, 57.5],
  ["Concatenation of Consecutive Binary Numbers", "Medium", "Bit Manipulation", 1680, 55.2],
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Check if already seeded with enough problems
    const { count } = await supabase
      .from("problems")
      .select("*", { count: "exact", head: true });

    // Parse force param from request body
    let force = false;
    try {
      const body = await req.json();
      force = body?.force === true;
    } catch {}

    if (count && count > 900 && !force) {
      return new Response(
        JSON.stringify({ success: true, message: `Already seeded with ${count} problems` }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Clear existing
    await supabase.from("problems").delete().gte("id", 0);

    // Deduplicate by title+topic (keep first occurrence)
    const seen = new Set<string>();
    const uniqueProblems: typeof ALL_PROBLEMS = [];
    for (const p of ALL_PROBLEMS) {
      const key = `${p[0]}|${p[2]}`;
      if (!seen.has(key)) {
        seen.add(key);
        uniqueProblems.push(p);
      }
    }

    // Build insert rows
    const rows = uniqueProblems.map((p, i) => ({
      title: p[0],
      difficulty: p[1],
      topic: p[2],
      tags: [p[2]],
      description: `Solve the "${p[0]}" problem.`,
      examples: [{ input: "See problem statement", output: "See problem statement" }],
      constraints: ["See full problem on LeetCode"],
      acceptance_rate: p[4],
      starter_code: {
        python: `class Solution:\n    def solve(self):\n        pass`,
        java: `class Solution {\n    public void solve() {\n    }\n}`,
        cpp: `class Solution {\npublic:\n    void solve() {\n    }\n};`,
        javascript: `var solve = function() {\n};`,
      },
      leetcode_number: p[3],
      problem_set: "neetcode_all",
    }));

    // Insert in batches of 100
    const batchSize = 100;
    let inserted = 0;
    for (let i = 0; i < rows.length; i += batchSize) {
      const batch = rows.slice(i, i + batchSize);
      const { error } = await supabase.from("problems").insert(batch);
      if (error) {
        console.error(`Batch ${i} error:`, error);
        return new Response(
          JSON.stringify({ success: false, error: error.message, batch: i }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      inserted += batch.length;
    }

    return new Response(
      JSON.stringify({ success: true, message: `Seeded ${inserted} problems` }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Seed error:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
